---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: org.grails.jaxrs.swagger
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
